apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.forgePostgresql.name }}-credentials
  labels:
    app.kubernetes.io/name: {{ .Values.forgePostgresql.name }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.forgePostgresql.auth.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.forgePostgresql.auth.database | quote }}
  POSTGRES_USER: "postgres"
  DATABASE_URL: "postgresql://postgres:{{ .Values.forgePostgresql.auth.postgresPassword }}@{{ .Values.forgePostgresql.name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.forgePostgresql.service.port }}/{{ .Values.forgePostgresql.auth.database }}"
