apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.forgeAdmin.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.forgeAdmin.name }}
spec:
  replicas: {{ .Values.forgeAdmin.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.forgeAdmin.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.forgeAdmin.name }}
    spec:
      containers:
      - name: {{ .Values.forgeAdmin.name }}
        image: "{{ .Values.forgeAdmin.image.repository }}:{{ .Values.forgeAdmin.image.tag }}"
        imagePullPolicy: {{ .Values.forgeAdmin.image.pullPolicy }}
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10
