forgePostgresql:
  name: forge-postgresql

  image:
    repository: postgres
    tag: "17"
    pullPolicy: IfNotPresent

  auth:
    database: "forge_platform"
    existingSecret: "forge-postgresql-credentials"
    passwordKey: "POSTGRES_PASSWORD"
    databaseKey: "POSTGRES_DB"
    userKey: "POSTGRES_USER"
    databaseUrlKey: "DATABASE_URL"

  service:
    type: ClusterIP
    port: 5432

  persistence:
    size: 8Gi
    storageClass: local-path

  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "512Mi"
