forgePostgresql:
  name: forge-postgresql

  image:
    repository: postgres
    tag: "17"
    pullPolicy: IfNotPresent

  auth:
    postgresPassword: "forge-secret-password"
    database: "forge_platform"

  service:
    type: ClusterIP
    port: 5432

  persistence:
    size: 8Gi
    storageClass: local-path

  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "512Mi"
